version: "3.8"

services:
  chess-api:
    build: .
    container_name: chess-api
    ports:
      - "3000:3000"
    networks:
      - chess-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - chess-net
    depends_on:
      - chess-api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - chess-net
    depends_on:
      - prometheus

networks:
  chess-net:
    driver: bridge
